name: Git Package Release

on:
  push:
    branches: [ main ]

env:
  flutter_version: '3.19.5'
  java_version: 17
  flutter_channel: 'stable'
  ruby_version: '2.7.5'
  release_version: '2.1.3'

jobs:
  git_package_release:
    name: Test & Release Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Setup Ruby (Install and Cache bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}
          bundler-cache: true

      - name: Setup Java 17
        uses: actions/setup-java@v3.11.0
        with:
          java-version: ${{ env.java_version }}
          distribution: 'zulu'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: ${{ env.flutter_channel }}
          cache: false

      - name: Create Release Notes
        env:
          BEFORE_REF: ${{ github.event.before }}
          AFTER_REF: ${{ github.event.after }}
        run: |
          echo "$(git log --pretty=format:'%s: %an' $BEFORE_REF...$AFTER_REF)" >> release_notes.md
          echo -e "\n$(date +'%Y-%m-%d')" >> release_notes.md
          cat release_notes.md

      - name: Publish to Github Releases
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          # commit: ${{ vars.RELEASE_TARGET_BRANCH }}
          # tag: ${{ env.release_version }}.${{ github.run_number }}
          tag: ${{ env.release_version }}
